spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://us-cdbr-east-03.cleardb.com/heroku_30341e67623ea5a?reconnect=true
    username: bb0b9228819b47
    password: 6259abe8
    
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    
logging:
  level:
    org:
      springframework: WARN
    com.example.kansyoku_kiroku.model.mapper: DEBUG